#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_LICENSES.md from the installed dependencies.

The plugin ships a single bundled `dist/index.js`. Some dependencies are
compiled *into* that file and are therefore redistributed with the
plugin; others are externalised at build time to globals Steam already
provides, and are not redistributed at all. Only the former need their
notices carried, and MIT in particular requires exactly that.

Generated rather than hand-written so the notices cannot drift from the
versions actually installed. Run after changing dependencies:

    python3 scripts/generate_third_party_licenses.py
"""

from __future__ import annotations

import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NODE_MODULES = os.path.join(REPO_ROOT, "node_modules")
OUTPUT = os.path.join(REPO_ROOT, "THIRD_PARTY_LICENSES.md")

#: Packages whose code is compiled into dist/index.js and so is
#: redistributed inside the plugin ZIP.
BUNDLED = (
    ("@decky/api", "Decky's plugin API; its client is compiled into the bundle."),
    ("i18next", "Translation runtime."),
    ("react-icons", "The plugin's menu icon; the icon's path data is inlined."),
    ("tslib", "TypeScript runtime helpers, inlined by the compiler."),
)

#: Resolved at runtime to globals Steam already provides, so no code from
#: these packages is redistributed. Listed for completeness only.
EXTERNALISED = (
    ("@decky/ui", "DFL"),
    ("react", "SP_REACT"),
    ("react-dom", "SP_REACTDOM"),
)

LICENSE_FILENAMES = ("LICENSE", "LICENSE.txt", "LICENSE.md", "LICENCE", "COPYING", "COPYING.txt")


def read_manifest(package: str) -> dict:
    path = os.path.join(NODE_MODULES, package, "package.json")
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def read_license_text(package: str) -> str | None:
    directory = os.path.join(NODE_MODULES, package)
    for name in LICENSE_FILENAMES:
        path = os.path.join(directory, name)
        if os.path.isfile(path):
            with open(path, "r", encoding="utf-8", errors="replace") as handle:
                return handle.read().strip()
    return None


def main() -> int:
    if not os.path.isdir(NODE_MODULES):
        print("node_modules is missing; run `pnpm install` first.", file=sys.stderr)
        return 1

    lines: list[str] = [
        "# Third-party licenses",
        "",
        "SteamView itself is BSD-3-Clause; see [LICENSE](LICENSE).",
        "",
        "The plugin ships one bundled JavaScript file, `dist/index.js`. The",
        "packages below are compiled into it and are therefore redistributed",
        "with the plugin, so their notices are reproduced here in full.",
        "",
        "This file is generated by `scripts/generate_third_party_licenses.py`",
        "from the installed dependencies. Do not edit it by hand.",
        "",
        "## Summary",
        "",
        "| Package | Version | License |",
        "| --- | --- | --- |",
    ]

    resolved: list[tuple[str, dict, str | None, str]] = []
    missing: list[str] = []

    for package, note in BUNDLED:
        try:
            manifest = read_manifest(package)
        except (OSError, ValueError):
            missing.append(package)
            continue
        text = read_license_text(package)
        if text is None:
            missing.append(f"{package} (no LICENSE file)")
        resolved.append((package, manifest, text, note))
        lines.append(
            f"| `{package}` | {manifest.get('version', '?')} | {manifest.get('license', 'see below')} |"
        )

    lines += [
        "",
        "### Not redistributed",
        "",
        "These are resolved at build time to globals the Steam client already",
        "provides, so no code from them is included in the bundle:",
        "",
    ]
    for package, global_name in EXTERNALISED:
        lines.append(f"- `{package}` &rarr; `window.{global_name}`")

    lines += ["", "---", ""]

    for package, manifest, text, note in resolved:
        lines += [
            f"## {package} {manifest.get('version', '')}".rstrip(),
            "",
            note,
            "",
            f"License: **{manifest.get('license', 'see notice below')}**",
        ]
        homepage = manifest.get("homepage")
        if isinstance(homepage, str) and homepage:
            lines += ["", f"Homepage: {homepage}"]
        lines += ["", "```", text or "(no license file shipped with this package)", "```", ""]

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines).rstrip() + "\n")

    print(f"Wrote {OUTPUT} covering {len(resolved)} bundled packages.")
    if missing:
        print("WARNING: could not fully resolve: " + ", ".join(missing), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
